FROM dunglas/frankenphp:1.1-php8.2

# Install official PHP extensions needed for Laravel & MySQL
RUN install-php-extensions \
    pdo_mysql \
    bcmath \
    pcntl \
    intl \
    zip \
    opcache

WORKDIR /app