name: Deploy FinTrack Production

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: |
          cd ~/fintrack || exit 1
          git fetch origin
          git checkout release
          git reset --hard origin/release

          # Build and start container
          docker compose -f docker-compose.prod.yml up -d --build

          # Run optimizations & migrations inside container
          docker exec fintrack_prod_web composer install --no-dev --optimize-autoloader --no-interaction
          docker exec fintrack_prod_web php artisan config:cache
          docker exec fintrack_prod_web php artisan route:cache
          docker exec fintrack_prod_web php artisan view:cache
          docker exec fintrack_prod_web php artisan migrate --force